name: Reproducibility CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Generate figures
        run: |
          mkdir -p figures
          python code/generate_figures.py

      - name: Upload figures artifact
        uses: actions/upload-artifact@v4
        with:
          name: figures
          path: figures/

      - name: Setup TeX Live (small)
        uses: dante-ev/texlive-action@v2
        with:
          profile: small

      - name: Compile LaTeX
        working-directory: paper
        run: |
          latexmk -pdf -silent main.tex

      - name: Upload paper PDF
        uses: actions/upload-artifact@v4
        with:
          name: paper-pdf
          path: paper/main.pdf
